// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMhVaENi5uDnGazWyKn9BWHAddjMnfybI',
    appId: '1:748968496912:web:51ec7ce5c92cfe6cff1f95',
    messagingSenderId: '748968496912',
    projectId: 'foodapp-777d6',
    authDomain: 'foodapp-777d6.firebaseapp.com',
    storageBucket: 'foodapp-777d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL4lFFJQYndF4VqvLBPNAJd2xFpKAQpOw',
    appId: '1:748968496912:android:f23b4c2081220031ff1f95',
    messagingSenderId: '748968496912',
    projectId: 'foodapp-777d6',
    storageBucket: 'foodapp-777d6.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrhywYHpeJR5bQXJb2R8zSlRh5aiL_YqE',
    appId: '1:748968496912:ios:37fb769d83b16dd2ff1f95',
    messagingSenderId: '748968496912',
    projectId: 'foodapp-777d6',
    storageBucket: 'foodapp-777d6.firebasestorage.app',
    iosClientId: '748968496912-ppncp5r26c10rkvourcn3aoct06db52n.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMhVaENi5uDnGazWyKn9BWHAddjMnfybI',
    appId: '1:748968496912:web:8438152b7035b1c5ff1f95',
    messagingSenderId: '748968496912',
    projectId: 'foodapp-777d6',
    authDomain: 'foodapp-777d6.firebaseapp.com',
    storageBucket: 'foodapp-777d6.firebasestorage.app',
  );
}
